### ISSUE TITLE
"grpc_message":"Received message larger than max 

### ISSUE THREAD

**Issue by cgy-dayup** [ray-project/lightgbm_ray#28]
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "Received message larger than max (210771146 vs. 104857600)"
	debug_error_string = "{"created":"@1646188124.309444695","description":"Error received from peer ipv4:10.207.183.32:40455","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Received message larger than max (210771146 vs. 104857600)","grpc_status":8}"

**Comment by cgy-dayup** [comment]
when i want to test the demo using my own dataset,i come across the problem?

**Comment by Yard1** [comment]
Let's use this one - https://github.com/ray-project/xgboost_ray/issues/201
