### ISSUE TITLE
Ray lightgbm reproducibility issue

### ISSUE THREAD

**Issue by vijaymobile123** [ray-project/lightgbm_ray#34]
@Yard1  Hi Sir, I was trying Light GBM Ray on a large dataset with 3 num actors and 3 CPUs per actor. With this context, the result keeps changing across different runs. Can you guide how to make results reproducable in LightGBM-Ray ?

I have set the following seeds:

Lightgbm random state seed

import numpy as np
np.random.seed(seed)
        
import random as python_random
python_random.seed(seed)

Any more seeds or parameters to set ?

**Comment by Yard1** [comment]
Setting the random seed in that way will not change anything as it will not apply to the lightgbm ray worker processes. Try setting the `random_state` parameter of the model to an integer instead.

**Comment by vijaymobile123** [comment]
Thanks @Yard1 . Setting `deterministic=True` is able to reproduce similar results. However, when I compare the model trained separately vs the model trained as part of HPO (ray tune) - I see the difference in the result for the same parameters, data, seed, and setting `deterministic=True`.  

For ray tune, I use the BasicVariantGenetator with grid search.

Any suggestions to make the results reproducible across HPO vs the normal run.

**Comment by vijaymobile123** [comment]
Hi @Yard1 - I figured out the issue. I was using spark for data preprocessing. Hence there was a difference in the ordering of the data (rowwise) which creates some nondeterminism. When I keep the input processed dataset sorted and the same across trials, then the results look similar.. Is this behavior expected ?


We can close this issue.

**Comment by Yard1** [comment]
Glad to hear it!
